name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  formz: ^0.6.0
  dio: ^5.2.1
  meta: ^1.9.1
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  subtree:
    path: ../..

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
