name: subtree
description: A new Flutter package project.
version: 0.1.0
homepage: https://github.com/vkubiv/subtree

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.1


flutter:

